language: swift #1
osx_image: xcode12u #2

install:
- gem install xcpretty
- gem install cocoapods
- pod install

jobs:
  include:
    - script: xcodebuild clean build test -project "Covid-19.xcodeproj" -scheme "Covid-19" -destination "platform=iOS Simulator,name=iPhone 11,OS=14.0" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO ONLY_ACTIVE_ARCH=NO -enableCodeCoverage YES | xcpretty -c
      after_script: bash <(curl -s https://codecov.io/bash)
    - script: swiftlint



