//
//  DataSetResponseDTO.swift
//  Covid-19
//
//  Created by eldin smakic on 11/08/2020.
//  Copyright © 2020 eldin smakic. All rights reserved.
//

public struct DataSetResponseDTO: Decodable {
    
    public let AFG: CovidResponseDTO
    public let ALB: CovidResponseDTO
//    public let DZA: CovidResponseDTO
//    public let AND: CovidResponseDTO
//    public let AGO: CovidResponseDTO
//    public let AIA: CovidResponseDTO
//    public let ATG: CovidResponseDTO
//    public let ARG: CovidResponseDTO
//    public let ARM: CovidResponseDTO
//    public let ABW: CovidResponseDTO
//    public let AUS: CovidResponseDTO
//    public let AUT: CovidResponseDTO
//    public let AZE: CovidResponseDTO
//    public let BHS: CovidResponseDTO
//    public let BHR: CovidResponseDTO
//    public let BGD: CovidResponseDTO
//    public let BRB: CovidResponseDTO
//    public let BLR: CovidResponseDTO
//    public let BEL: CovidResponseDTO
//    public let BLZ: CovidResponseDTO
//    public let BEN: CovidResponseDTO
//    public let BMU: CovidResponseDTO
//    public let BTN: CovidResponseDTO
//    public let BOL: CovidResponseDTO
//    public let BES: CovidResponseDTO
//    public let BIH: CovidResponseDTO
//    public let BWA: CovidResponseDTO
//    public let BRA: CovidResponseDTO
//    public let VGB: CovidResponseDTO
//    public let BRN: CovidResponseDTO
//    public let BGR: CovidResponseDTO
//    public let BFA: CovidResponseDTO
//    public let BDI: CovidResponseDTO
//    public let KHM: CovidResponseDTO
//    public let CMR: CovidResponseDTO
//    public let CAN: CovidResponseDTO
//    public let CPV: CovidResponseDTO
//    public let CYM: CovidResponseDTO
//    public let CAF: CovidResponseDTO
//    public let TCD: CovidResponseDTO
//    public let CHL: CovidResponseDTO
//    public let CHN: CovidResponseDTO
//    public let COL: CovidResponseDTO
//    public let COM: CovidResponseDTO
//    public let COG: CovidResponseDTO
//    public let CRI: CovidResponseDTO
//    public let CIV: CovidResponseDTO
//    public let HRV: CovidResponseDTO
//    public let CUB: CovidResponseDTO
//    public let CUW: CovidResponseDTO
//    public let CYP: CovidResponseDTO
//    public let CZE: CovidResponseDTO
//    public let COD: CovidResponseDTO
//    public let DNK: CovidResponseDTO
//    public let DJI: CovidResponseDTO
//    public let DMA: CovidResponseDTO
//    public let DOM: CovidResponseDTO
//    public let ECU: CovidResponseDTO
//    public let EGY: CovidResponseDTO
//    public let SLV: CovidResponseDTO
//    public let GNQ: CovidResponseDTO
//    public let ERI: CovidResponseDTO
//    public let EST: CovidResponseDTO
//    public let ETH: CovidResponseDTO
//    public let FRO: CovidResponseDTO
//    public let FLK: CovidResponseDTO
//    public let FJI: CovidResponseDTO
//    public let FIN: CovidResponseDTO
//    public let FRA: CovidResponseDTO
//    public let PYF: CovidResponseDTO
//    public let GAB: CovidResponseDTO
//    public let GMB: CovidResponseDTO
//    public let GEO: CovidResponseDTO
//    public let DEU: CovidResponseDTO
//    public let GHA: CovidResponseDTO
//    public let GIB: CovidResponseDTO
//    public let GRC: CovidResponseDTO
//    public let GRL: CovidResponseDTO
//    public let GRD: CovidResponseDTO
//    public let GUM: CovidResponseDTO
//    public let GTM: CovidResponseDTO
//    public let GGY: CovidResponseDTO
//    public let GIN: CovidResponseDTO
//    public let GNB: CovidResponseDTO
//    public let GUY: CovidResponseDTO
//    public let HTI: CovidResponseDTO
//    public let HND: CovidResponseDTO
//    public let HKG: CovidResponseDTO
//    public let HUN: CovidResponseDTO
//    public let ISL: CovidResponseDTO
//    public let IND: CovidResponseDTO
//    public let IDN: CovidResponseDTO
//    public let IRN: CovidResponseDTO
//    public let IRQ: CovidResponseDTO
//    public let IRL: CovidResponseDTO
//    public let IMN: CovidResponseDTO
//    public let ISR: CovidResponseDTO
//    public let ITA: CovidResponseDTO
//    public let JAM: CovidResponseDTO
//    public let JPN: CovidResponseDTO
//    public let JEY: CovidResponseDTO
//    public let JOR: CovidResponseDTO
//    public let KAZ: CovidResponseDTO
//    public let KEN: CovidResponseDTO
//    public let OWI: CovidResponseDTO
//    public let KWT: CovidResponseDTO
//    public let KGZ: CovidResponseDTO
//    public let LAO: CovidResponseDTO
//    public let LVA: CovidResponseDTO
//    public let LBN: CovidResponseDTO
//    public let LSO: CovidResponseDTO
//    public let LBR: CovidResponseDTO
//    public let LBY: CovidResponseDTO
//    public let LIE: CovidResponseDTO
//    public let LTU: CovidResponseDTO
//    public let LUX: CovidResponseDTO
//    public let MKD: CovidResponseDTO
//    public let MDG: CovidResponseDTO
//    public let MWI: CovidResponseDTO
//    public let MYS: CovidResponseDTO
//    public let MDV: CovidResponseDTO
//    public let MLI: CovidResponseDTO
//    public let MLT: CovidResponseDTO
//    public let MRT: CovidResponseDTO
//    public let MUS: CovidResponseDTO
//    public let MEX: CovidResponseDTO
//    public let MDA: CovidResponseDTO
//    public let MCO: CovidResponseDTO
//    public let MNG: CovidResponseDTO
//    public let MNE: CovidResponseDTO
//    public let MSR: CovidResponseDTO
//    public let MAR: CovidResponseDTO
//    public let MOZ: CovidResponseDTO
//    public let MMR: CovidResponseDTO
//    public let NAM: CovidResponseDTO
//    public let NPL: CovidResponseDTO
//    public let NLD: CovidResponseDTO
//    public let NCL: CovidResponseDTO
//    public let NZL: CovidResponseDTO
//    public let NIC: CovidResponseDTO
//    public let NER: CovidResponseDTO
//    public let NGA: CovidResponseDTO
//    public let MNP: CovidResponseDTO
//    public let NOR: CovidResponseDTO
//    public let OMN: CovidResponseDTO
//    public let PAK: CovidResponseDTO
//    public let PSE: CovidResponseDTO
//    public let PAN: CovidResponseDTO
//    public let PNG: CovidResponseDTO
//    public let PRY: CovidResponseDTO
//    public let PER: CovidResponseDTO
//    public let PHL: CovidResponseDTO
//    public let POL: CovidResponseDTO
//    public let PRT: CovidResponseDTO
//    public let PRI: CovidResponseDTO
//    public let QAT: CovidResponseDTO
//    public let ROU: CovidResponseDTO
//    public let RUS: CovidResponseDTO
//    public let RWA: CovidResponseDTO
//    public let KNA: CovidResponseDTO
//    public let LCA: CovidResponseDTO
//    public let VCT: CovidResponseDTO
//    public let SMR: CovidResponseDTO
//    public let STP: CovidResponseDTO
//    public let SAU: CovidResponseDTO
//    public let SEN: CovidResponseDTO
//    public let SRB: CovidResponseDTO
//    public let SYC: CovidResponseDTO
//    public let SLE: CovidResponseDTO
//    public let SGP: CovidResponseDTO
//    public let SXM: CovidResponseDTO
//    public let SVK: CovidResponseDTO
//    public let SVN: CovidResponseDTO
//    public let SOM: CovidResponseDTO
//    public let ZAF: CovidResponseDTO
//    public let KOR: CovidResponseDTO
//    public let SSD: CovidResponseDTO
//    public let ESP: CovidResponseDTO
//    public let LKA: CovidResponseDTO
//    public let SDN: CovidResponseDTO
//    public let SUR: CovidResponseDTO
//    public let SWZ: CovidResponseDTO
//    public let SWE: CovidResponseDTO
//    public let CHE: CovidResponseDTO
//    public let SYR: CovidResponseDTO
//    public let TWN: CovidResponseDTO
//    public let TJK: CovidResponseDTO
//    public let TZA: CovidResponseDTO
//    public let THA: CovidResponseDTO
//    public let TLS: CovidResponseDTO
//    public let TGO: CovidResponseDTO
//    public let TTO: CovidResponseDTO
//    public let TUN: CovidResponseDTO
//    public let TUR: CovidResponseDTO
//    public let TCA: CovidResponseDTO
//    public let UGA: CovidResponseDTO
//    public let UKR: CovidResponseDTO
//    public let ARE: CovidResponseDTO
//    public let GBR: CovidResponseDTO
//    public let USA: CovidResponseDTO
//    public let VIR: CovidResponseDTO
//    public let URY: CovidResponseDTO
//    public let UZB: CovidResponseDTO
//    public let VAT: CovidResponseDTO
//    public let VEN: CovidResponseDTO
//    public let VNM: CovidResponseDTO
//    public let ESH: CovidResponseDTO
//    public let YEM: CovidResponseDTO
//    public let ZMB: CovidResponseDTO
//    public let ZWE: CovidResponseDTO
//    public let OWIDWRL: CovidResponseDTO
}
